services:
  leofee-test-db:
    image: mysql
    container_name: leofee-test-db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - leofee-test-mssql-data:/var/opt/mysql
    ports:
      - 3306:3306
    networks:
      - leofee-test-network

  leofee-test-adminer:
    image: adminer
    container_name: leofee-test-adminer
    ports:
      - 8083:8080
    networks:
      - leofee-test-network
    depends_on: 
      - leofee-test-db

  leofee-test-web:
    image: nginx
    container_name: leofee-test-web-nginx
    ports:
      - 8087:80
    networks:
      - leofee-test-network

  leofee-test-backend:
    image: samuel010203/leofee-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leofee-test-backend
    ports:
      - 8088:8080
    networks:
      - leofee-test-network
    depends_on:
      - leofee-test-db

  leofee-test-dashboard:
    image: samuel010203/dashboard
    container_name: leofee-test-dashboard
    ports:
      - 8089:8080
    networks:
      - leofee-test-network
    depends_on:
      - leofee-test-db

volumes:
  leofee-test-mssql-data:
    

networks:
  leofee-test-network:
    name: leofee-test-network
    driver: bridge
    external: false
    ipam:
      config:
        - subnet: 10.7.0.0/16
