@baseURL=https://vm64.htl-leonding.ac.at/leofee-backend/api

###
GET {{baseURL}}/Ping

### recreate database
PATCH {{baseURL}}/Ping

### get bons
GET {{baseURL}}/bon

###
GET {{baseURL}}/WhiteListUser

###
GET {{baseURL}}/Transaction


###
POST https://vm64.htl-leonding.ac.at/leofee-backend/pay?amount=1&studentId=IF200177


###
GET {{baseURL}}/Bon