@baseURL=https://vm64.htl-leonding.ac.at/leofee-backend/api

###
GET {{baseURL}}/Ping

### recreate database
PATCH {{baseURL}}/Ping

### get bons
GET {{baseURL}}/bons

###
GET {{baseURL}}/WhiteListUser

###
GET {{baseURL}}/Transactions

###
GET {{baseURL}}/students/if200145/bons


###
POST https://vm64.htl-leonding.ac.at/leofee-backend/pay?amount=1&studentId=IF200177


###
GET {{baseURL}}/Bons