version: '3.8'

services:
  leofee-test-db:
    image: mysql:5.7 #mysql:5.6
    container_name: leofee-test-db
    restart: always
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'leofeedb'
      MYSQL_PASSWORD: 'password'
    volumes:
      - leofee_leofee-mysql-data:/var/lib/mysql
    networks:
      - tadeotnet

  leofee-test-adminer:
    image: adminer
    container_name: leofee-test-adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leofee-test-adminer.rule=Host(`vm45.htl-leonding.ac.at`) && PathPrefix(`/adminer`)"
      - "traefik.http.services.leofee-test-adminer.loadbalancer.server.port=8080"
    depends_on:
      - leofee-test-db
    networks:
      - tadeotnet

  leofee-test-backend:
    image: samuel010203/leofee-backend:latest
    container_name: leofee-test-backend
    restart: always
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=tadeotnet"
      - "traefik.http.routers.leofee-test-backend.rule=Host(`vm45.htl-leonding.ac.at`) && PathPrefix(`/leofee-backend`)"
      - "traefik.http.services.leofee-test-backend.loadbalancer.server.port=5015"
    networks:
      - tadeotnet


  leofee-test-dashboard:
    #image: brudermichael07/dashboard
    image: samuel010203/dashboard
    container_name: leofee-test-dashboard
    restart: always
    environment:
      httpUrlLeofeeBackend: "https://vm45.htl-leonding.ac.at/leofee-backend/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leofee-test-dashboard.rule=Host(`vm45.htl-leonding.ac.at`) && PathPrefix(`/dashboard`)"
      - "traefik.http.middlewares.leofee-test-dashboard-strip-prefix.stripprefix.prefixes=/dashboard"
      - "traefik.http.routers.leofee-test-dashboard.middlewares=leofee-test-dashboard-strip-prefix"
      - "traefik.http.services.leofee-test-dashboard.loadbalancer.server.port=80"
    networks:
      - tadeotnet

  leofee-test-smobile:
    restart: always
    #image: brudermichael07/s-mobile
    image: samuel010203/s-mobile
    container_name: leofee-test-smobile
    environment:
      httpUrlLeofeeBackend: "https://vm45.htl-leonding.ac.at/leofee-backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leofee-test-smobile.rule=Host(`vm45.htl-leonding.ac.at`) && PathPrefix(`/s-mobile`)"
      - "traefik.http.services.leofee-test-smobile.loadbalancer.server.port=80"
      - "traefik.http.middlewares.leofee-smobile-strip-prefix.stripprefix.prefixes=/s-mobile"
      - "traefik.http.routers.leofee-test-smobile.middlewares=leofee-smobile-strip-prefix"
    networks:
      - tadeotnet

  leofee-test-kassa-app:
    restart: always
    image: brudermichael07/kassa-app
    container_name: leofee-test-kassa-app
    environment:
      httpUrlLeofeeBackend: "https://vm45.htl-leonding.ac.at/leofee-backend/"
      httpUrlTadeotBackend: "https://tadeot.htl-leonding.ac.at/tadeot-api/api/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leofee-test-kassa-app.rule=Host(`vm45.htl-leonding.ac.at`) && PathPrefix(`/kassa`)"
      - "traefik.http.services.leofee-test-kassa-app.loadbalancer.server.port=80"
      - "traefik.http.middlewares.leofee-kassa-app-strip-prefix.stripprefix.prefixes=/kassa"
      - "traefik.http.routers.leofee-test-kassa-app.middlewares=leofee-kassa-app-strip-prefix"
    networks:
      - tadeotnet

volumes:
  leofee_leofee-mysql-data:

networks:
  tadeotnet:
    external: true
    name: tadeotnet
