FROM node:20 AS builder
WORKDIR /app
COPY ./package*.json .
RUN npm install 
COPY . .
RUN npm run build

FROM nginx:1.17.1-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/dist/kassa .
