GET http://localhost:5196/students
Accept: application/json


###

GET http://localhost:5196/students/{id}
Accept: application/json

###

GET http://localhost:5196/student/{id}/balance
Accept: application/json

###

GET http://localhost:5196/student/{studentString}/getId
Accept: application/json

###

POST http://localhost:5196/student/{id}/pay/{value}
Content-Type: application/json

{
  "id": "{id}",
  "value": {value}
}