name: Docker build & push

on:
  push:
    branches:
      - main
      - fixes-GithubActions  

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for dashboard
        uses: docker/build-push-action@v2
        with:
          context: ./dashboard
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository | toLowerCase }}:dashboard

      - name: Docker Build frontend - kassa-app
        uses: docker/build-push-action@v2
        with:
          context: ./kassa-app
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository | toLowerCase }}:kassa-app

      - name: Docker Build frontend - s-mobile-keycloak
        uses: docker/build-push-action@v2
        with:
          context: ./s-mobile-keycloak/s-mobile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository | toLowerCase }}:s-mobile-keycloak

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository | toLowerCase }}:backend
