name: Docker build & push

on:
  push:
    branches:
      - main
      - fixes-GithubActions

permissions:
  contents: read  # Allows reading the contents of the repository (default)
  packages: write # Allows publishing Docker images to GitHub Packages
  id-token: write # Needed for container image publishing

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set IMAGE_PREFIX to lowercase
        id: lowercase
        run: |
          echo "IMAGE_PREFIX=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for dashboard
        uses: docker/build-push-action@v2
        with:
          context: ./dashboard/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}:dashboard

      - name: Docker Build frontend - kassa-app
        uses: docker/build-push-action@v2
        with:
          context: ./kassa-app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}:kassa-app

      - name: Docker Build frontend - s-mobile-keycloak
        uses: docker/build-push-action@v2
        with:
          context: ./s-mobile-keycloak/s-mobile/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}:s-mobile-keycloak

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend/tdot-backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}:backend
