name: Dockerhub-publish

on:
  push:
    branches: 
      - main
      - fixes-GithubActions

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io  #  ghcr.io  entfernt
  # github.repository as <account>/<repo>
  IMAGE_NAME_DASHBOARD: ${{ secrets.DOCKERHUB_USERNAME }}/leohoot-dashboard  #  Neuer Name für Dashboard-Image
  IMAGE_NAME_KASSA_APP: ${{ secrets.DOCKERHUB_USERNAME }}/leohoot-kassa-app  #  Neuer Name für kassa-app Image
  IMAGE_NAME_S_MOBILE_KEYCLOAK: ${{ secrets.DOCKERHUB_USERNAME }}/leohoot-s-mobile-keycloak  #  Neuer Name für s-mobile-keycloak Image
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/leohoot-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard  #  Korrigierter Kontext
          push: true
          tags: ${{ env.IMAGE_NAME_DASHBOARD }}  #  Neuer Image-Name

      - name: Docker Build kassa-app
        uses: docker/build-push-action@v4
        with:
          context: ./kassa-app  #  Korrigierter Kontext
          push: true
          tags: ${{ env.IMAGE_NAME_KASSA_APP }}  #  Neuer Image-Name

      - name: Docker Build s-mobile-keycloak
        uses: docker/build-push-action@v4
        with:
          context: ./s-mobile-keycloak/s-mobile  #  Korrigierter Kontext
          push: true
          tags: ${{ env.IMAGE_NAME_S_MOBILE_KEYCLOAK }}  #  Neuer Image-Name

      - name: Docker Build backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend/tdot-backend  #  Korrigierter Kontext
          push: true
          tags: ${{ env.IMAGE_NAME_BACKEND }}