name: Lint

on:
  push:
    branches:
      - 154-lint-und-code-coverage-einfügen
  pull_request:
    branches:
      - 154-lint-und-code-coverage-einfügen

permissions:
  contents: write
  packages: write
  statuses: write
  checks: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install TypeScript globally
        run: npm install -g typescript

      - name: Show installed npm packages
        run: npm list --all
      
      - name: Show ESLint version
        run: npx eslint --version

      - name: Run Prettier on project-a
        run: npx prettier --check ./s-mobile-keycloak/s-mobile

      - name: Run ESLint on project-a
        run: npx eslint ./s-mobile-keycloak/s-mobile
